version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jwt_api
      POSTGRES_USER: baris
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
